void remove_spaces(char *);
int count_tabs(char *);
char *mode_recognise(char *,int *);
int vailable_names(char *);
treeptr create_var(treeptr,char *);
void treeprint(treeptr);
int expression_exist(char **);
int is_constant(char *);
int get_value(treeptr,char *);
treeptr put_var(treeptr,char *,int);
void add_line(listptr *,char *,int);
void list_print(listptr);
void condition_print(listptrc);
void add_condition(listptrc *,int,int,int *);
int var_exist(treeptr, char *);
int variable_mode(char **,treeptr *,int,int);
int all_modes(treeptr *,listptr *,int,int *,int *,listptrc *,int,int *,int);
int condition_mode(char **,int,int,treeptr *);
int get_condition(listptrc, int *);
void delete_condition(listptrc *,int *);
int get_condition_by_tabs(listptrc,int);
int get_tabs(listptrc,int);
void cond_0(listptrc,int);
int read_func(char *,treeptr *,int,int);
int write_func(char **,treeptr *,int,int,int);
int rand_func(char **,treeptr *,int,int);
int argument_1(char **,treeptr *,int,int,int,int *);
int argument_2(char **,treeptr *,int,int,int,int *);